name: awesome_wallpaper
description: Awesome wallpapers for your device.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http:
  esys_flutter_share:
  wallpaper_manager: "^1.0.10"
  flutter_cache_manager: "^1.1.3"
  dynamic_theme:
  font_awesome_flutter: 8.8.1
  url_launcher: 5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
